name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libboost-dev
        cmake .
    - name: make
      run: make
